import Head from 'next/head'
import {BsFillMoonStarsFill} from'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import Image from "next/image";
import bashar from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next-Awesome Portfolio</title>
        <meta name="description" content="Generated by Next Awesome Portfolio" />
        <link rel="icon" href="/icon.jpg" />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>ASAD</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl' /></li>
              <li><a className=' bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
            </ul>
          </nav>

          <div className=' text-center p-10'>
            <h2 className=' text-5xl py-2 text-teal-600 font-medium'>Bashar Ahmad</h2>
            <h3 className=' text-2xl py-2'>Front-End Engineer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>I am a Front-End Engineer with experience in building websites and web applications. I specialize in various JavaScript front framework like Angular, React & Vue. I've also worked with other technologies including Ruby on Rails, Django, and Flask.</p>
          </div>
          <div className=' text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle /> 
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={bashar} layout="fill" objectFit="cover"/>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1' >Services I offer</h3>
            <p className='ext-md py-5 leading-8 text-gray-800'>
              Portfolio <spam className=" text-teal-500">website</spam> for any profession like Artist, Singer, Doctor, Engineer, Lowyer, Designer, etc.
              Make Packages like Animation, Transition & Color Grading for looking gorgious.
              You can change style, typography or theme anytime.
              Use some technologies for making your site SUPPER FAST
            </p>
          </div>
          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image className='m-auto' src={design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
              <p className='py-2'>Use some technologies for making your site SUPPER FAST</p>
              <h4 className='py-4 text-teal-600'>Tools I used</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illlustrator</p>
              <p className='text-gray-800 py-1'>ImageReady</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image className='m-auto' src={code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
              <p className='py-2'>Use some technologies for making your site SUPPER FAST</p>
              <h4 className='py-4 text-teal-600'>Tools I used</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illlustrator</p>
              <p className='text-gray-800 py-1'>ImageReady</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image className='m-auto' src={consulting} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
              <p className='py-2'>Use some technologies for making your site SUPPER FAST</p>
              <h4 className='py-4 text-teal-600'>Tools I used</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illlustrator</p>
              <p className='text-gray-800 py-1'>ImageReady</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='ext-md py-5 leading-8 text-gray-800'>
              Portfolio <spam className=" text-teal-500">website</spam> for any profession like Artist, Singer, Doctor, Engineer, Lowyer, Designer, etc.
              Make Packages like Animation, Transition & Color Grading for looking gorgious.
              You can change style, typography or theme anytime.
              Use some technologies for making your site SUPPER FAST
            </p>
          </div>
          <div>
            <div>
              <Image src={web1} />
            </div>
            <div>
              <Image src={web2} />
            </div>
            <div>
              <Image src={web3} />
            </div>
            <div>
              <Image src={web4} />
            </div>
            <div>
              <Image src={web5} />
            </div>
            <div>
              <Image src={web6} />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
